# golangci-lint configuration

run:
  timeout: 5m
  modules-download-mode: mod

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
